# Generated by Django 4.1 on 2022-08-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_date_of_birt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birt',
            new_name='date_of_birth',
        ),
    ]
